// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJxkZfWKa5YLdVqOo4G8O0yB9VZfAxuuY',
    appId: '1:827825103045:web:2929057861d171be48d0ac',
    messagingSenderId: '827825103045',
    projectId: 'instaui-f720b',
    authDomain: 'instaui-f720b.firebaseapp.com',
    storageBucket: 'instaui-f720b.appspot.com',
    measurementId: 'G-RQ2S2GP0Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_TWNDR1oadgYverm6_dpXSMs83x1bENo',
    appId: '1:827825103045:android:5313325bb9fcb8e748d0ac',
    messagingSenderId: '827825103045',
    projectId: 'instaui-f720b',
    storageBucket: 'instaui-f720b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhUtLCwjBXJ9V_9bPoaFk3GepXrDlC0d4',
    appId: '1:827825103045:ios:a83843bde439048b48d0ac',
    messagingSenderId: '827825103045',
    projectId: 'instaui-f720b',
    storageBucket: 'instaui-f720b.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhUtLCwjBXJ9V_9bPoaFk3GepXrDlC0d4',
    appId: '1:827825103045:ios:e69c5a1f7579593748d0ac',
    messagingSenderId: '827825103045',
    projectId: 'instaui-f720b',
    storageBucket: 'instaui-f720b.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
